### ISSUE TITLE
Misplaced Artifact in v1.0.4 Release

### ISSUE THREAD

**Issue by SableRaf** [doradocodes/processing-collab-editor#6]
Hello, Dora! I noticed an issue with the v1.0.4 release where the `Processing.Collaborative.Editor-darwin-arm64-1.0.0.zip` artifact  is mistakenly included in the assets for v1.0.4.

**Comment by doradocodes** [comment]
I'm actually in the process of renaming this build (since it's the first public launch, I wanted to start the versions at 1.0.0), so along with including the latest changes in the app, I'm replacing all the versions with 1.0.0 and getting rid of the 1.0.4 label. 
(Windows build is still in progress and will be replaces in this release soon).
